---

modules:
  - name: openwisp-controller
    dir_name: controller
  - name: openwisp-monitoring
    dir_name: monitoring
  - name: openwisp-firmware-upgrader
    dir_name: firmware-upgrader
  - name: openwisp-radius
    dir_name: radius
    # TODO: Remove before merging
    branch: reorder-docs
  - name: openwisp-notifications
    dir_name: notifications
  - name: openwisp-network-topology
    dir_name: network-topology
  - name: openwisp-users
    dir_name: users
  - name: openwisp-utils
    dir_name: utils
  - name: openwisp-wifi-login-pages
    dir_name: wifi-login-pages
  - name: openwisp-ipam
    dir_name: ipam
  - name: openwisp-config
    dir_name: openwrt-config-agent
  - name: openwrt-openwisp-monitoring
    dir_name: openwrt-monitoring-agent
  - name: ansible-openwisp2
    dir_name: ansible
    # TODO: Remove before merging
    branch: reorder-docs
  - name: docker-openwisp
    dir_name: docker
    # TODO: Remove before merging
    branch: reorder-docs
versions:
  - name: '22.05'
    overwrite_modules: true
    modules:
      - name: openwisp-docs
        branch: 'v22.05'
        dir_name: openwisp-docs
    sphinx_src_dir: ./openwisp-docs
  - name: dev
    branch: master
